name: Update Leaderboard

on:
  schedule:
    # Run daily at 6:00 AM UTC (before peak traffic)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggers
    inputs:
      force_update:
        description: 'Force update even if recent data exists'
        required: false
        default: 'false'

env:
  NODE_VERSION: '18'

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update leaderboard data
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          node scripts/update-leaderboard.js
        timeout-minutes: 10

      - name: Verify update
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: |
          node scripts/verify-leaderboard.js

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Leaderboard update failed"
          echo "Check the logs and fix the issue"